language: php

matrix:
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: hhvm
    - php: 7.0
  allow_failures:
    - php: 7.0
  fast_finish: true
  
before_script:
  - composer self-update
  - composer install -n

script:
  - vendor/bin/phpspec run --format=pretty
  - vendor/bin/behat
